# 2021 年度後期 実験 II 演習資料
2021.10.19  
岡田真  

# ```Numpy``` 数値演算ライブラリ

## 概要

```Numpy```: ```Python``` で数学的計算をするためのライブラリ．  
さまざまなところでよく使われている．  
TensorFlow や PyTorch など Deep Learning 系のフレームワークでも使っていて，  
行列やテンソルなどをこのライブラリの形式に準じた形で表したり，  
相互に変換する関数が用意されている．  
特に配列や行列を使うところ（通常はリスト）でよく使われる．  
```Python``` の泣き所である「繰り返しの遅さ」を軽減してくれる．  


In [1]:
import numpy as np # お約束として，np と名前を付けて使うことが多い

In [2]:
# 数学の関数もたくさんある
print(np.exp(2)) # e のべき乗
print(np.pi) # 定数 π (円周率)
print(np.e) # 定数 e (ネイピア数)
print(np.sin(0.5)) # 正弦関数
print(np.sqrt(2)) # 平方根

7.38905609893065
3.141592653589793
2.718281828459045
0.479425538604203
1.4142135623730951


## ```numpy``` の配列

```numpy``` の配列は ```ndarray``` クラス

In [3]:
a = np.array([2, 3, 5, 7, 8])
print(a[1:3])
print(a[2:-1])

[3 5]
[5 7]


In [4]:
# arrange による連続値を要素として持つ配列の生成
b = np.arange(5)
c = np.arange(1, 3, 0.2) # 刻み幅を 0.2 に設定
print(b)
print(c)

[0 1 2 3 4]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


In [5]:
# データの型 (int64, float64 など)
print(a.dtype)

d = np.array([1, 2, 3], dtype=np.float64)
print(d.dtype)

int64
float64


## ```numpy``` の 2 次元配列

リストのリストで 2 次元配列を表現する．  
インデックス 2 個（行番号と列番号）でアクセスする.  
（0 行目，1 行目 …… (m-1) 行目），（0 列目，1 列目，……，(n-1) 列目）

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print(a[0,1]) # 0 行 1 列目の要素

[[1 2 3]
 [4 5 6]]
2


重要なデータ属性がある

- ```shape```: 配列の形状  
- ```ndim```: 配列の次元
- ```size```: 要素数

In [8]:
a = np.arange(15.).reshape(3, 5) # 3 行 5 列の 2 次元行列
print(a)
print(a.size) # 配列の要素数
print(a.shape) # 配列の形状
print(a.ndim) # 配列の次元

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
15
(3, 5)
2


```reshape``` 関数は形状を変更できる．  
```reshape``` は一部の値を指定しなくても形状変更できる．

In [10]:
a = np.arange(16.) # 要素数 16 個
print(a)

a = a.reshape(4, -1) # 行だけ指定．列は自動設定 (-1) 
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


```ravel``` 関数は配列を 1 次元に戻す．  
```reshape(-1)``` でも同様になる．

In [11]:
a = a.ravel()
print(a)

a = a.reshape(4, -1)
print(a)

a = a.reshape(-1)
print(a)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


列数だけ指定することもできる．

In [13]:
a = np.arange(4.)
print(a)

a = a.reshape(-1, 1) # 1 列で指定
print(a)

[0. 1. 2. 3.]
[[0.]
 [1.]
 [2.]
 [3.]]


1 次元の配列と，行数 1 の 2 次元配列は違うことに注意する

In [14]:
a = a.reshape(-1)
print(a)

a = a.reshape(1, -1) # 1 行で指定
print(a)

[0. 1. 2. 3.]
[[0. 1. 2. 3.]]


## いろんな配列の作成

- ```zeros```: 要素がすべて 0 の配列を作る  
- ```ones```: 要素がすべて 1 の配列を作る
- ```empty```: 指定された形状の配列を作る（初期値は不定．空ではない場合もある）

In [17]:
a = np.zeros((3, 4))
print(a)

a = np.ones((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
a = np.empty((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 行列の連結
行方向の連結（横に長くなる）と，列方向の連結（縦に長くなる）がある．  
```r_[a,b]```: 列方向 (row) の連結  
```c_[a,b]```: 行方向 (column) の連結

形が合わないとエラーになるので，その場合は ```reshape``` で形をそろえてから連結する．

In [19]:
a = np.arange(0,6).reshape(2,-1)
b = np.arange(7,13).reshape(2,-1)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]


In [20]:
c = np.r_[a,b] # 列方向の連結，角カッコ ([]) に注意
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [21]:
c = np.c_[a,b] # 行方向の連結，角カッコ ([]) に注意
print(c)

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


# 配列の基本計算

## 集計関数

In [22]:
a = np.arange(5.)
print(a)

print(a.sum()) # 合計
print(a.max()) # 最大
print(a.min()) # 最小
print(a.mean()) # 平均

[0. 1. 2. 3. 4.]
10.0
4.0
0.0
2.0


2 次元配列でもできる．  
2 次元配列の場合は，軸を指定することもできる．

In [23]:
a = np.arange(9.0).reshape(3, 3)
print(a)

print(a.sum())
print(a.max())
print(a.min())
print(a.mean())

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
36.0
8.0
0.0
4.0


In [24]:
print(a.sum(axis=0)) # 行方向（列固定）に計算，列ごとに出る
print(a.sum(axis=1)) # 列方向（行固定）に計算，行ごとに出る

[ 9. 12. 15.]
[ 3. 12. 21.]


## ブロードキャスト
```Numpy``` の配列には，その配列を含んで演算する場合に，  
次元数や形状を自動的に調整する機能「ブロードキャスト」がある．

In [25]:
a = np.arange(3.,8.)
print(a)
print(np.exp(a))
print(np.log(a))
print(np.sqrt(a))

[3. 4. 5. 6. 7.]
[  20.08553692   54.59815003  148.4131591   403.42879349 1096.63315843]
[1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


演算が各要素に対しておこなわれていることがわかる．

In [26]:
b = np.arange(9.).reshape(3, 3)
print(b)

print(np.exp(b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]


演算子や条件式にも使える．

In [27]:
# 配列とスカラの演算
a = np.arange(5)
print(a)
print(a+3)
print(a*3)
print(a**2)
print(a>=2)
print(a!=3)


[0 1 2 3 4]
[3 4 5 6 7]
[ 0  3  6  9 12]
[ 0  1  4  9 16]
[False False  True  True  True]
[ True  True  True False  True]


In [28]:
b = np.arange(9).reshape(3,3)
print(b)
print(b>3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[False False False]
 [False  True  True]
 [ True  True  True]]


リスト内包表記でも同様のことができる．  
しかし，ブロードキャストの方が速い．

ブール値（```True```，```False```）を要素に持つ配列を配列の各カッコに入れると，  
```True``` に対応する要素だけ取り出すことができる．

In [29]:
a = np.array([10, 20, 30, 40])
b = np.array([False, True, True, False])

print(a[b])

[20 30]


In [30]:
c = np.array([[3,4,5], [6,7,8]])
d = np.array([[False, False, True], [False, True, True]])
print(c)
print(d)
print(c[d])

[[3 4 5]
 [6 7 8]]
[[False False  True]
 [False  True  True]]
[5 7 8]


この仕組みとブロードキャストを利用して，  
配列内のある条件に合った要素だけを抽出することができる．

In [31]:
a = np.arange(10)
print(a)
print(a[a>5])
print(a[(a>=3)&(a<6)])
print(a[(a<2) | (a>7)])
print(a[a % 3 != 0])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[3 4 5]
[0 1 8 9]
[1 2 4 5 7 8]


配列でブロードキャストさせるために ```and``` や ```or``` ではなく，  
```&``` や ```|``` を使うことに注意する

## 配列の演算
1 次元配列でも 2 次元配列でも配列同士の演算ができる．  
```np.dot()``` 関数で，2 つのベクトルの内積を計算できる．  
2 つのベクトルの積を得てから ```sum``` で挿話を取っても同じ値になる．   

1 次元配列

In [32]:
u = np.arange(4)
v = np.arange(3,7)

print(u)
print(v)

[0 1 2 3]
[3 4 5 6]


In [33]:
print(u+v)
print(u-v)
print(u*v)

[3 5 7 9]
[-3 -3 -3 -3]
[ 0  4 10 18]


In [34]:
print(np.dot(u,v))
print((u*v).sum())

32
32


2 次元配列 

In [35]:
a = np.arange(9.).reshape(3,3)
b = np.arange(4.,13.).reshape(3,3)
print(a)
print(b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


四則演算は要素ごとになる．

In [36]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 4.  6.  8.]
 [10. 12. 14.]
 [16. 18. 20.]]
[[-4. -4. -4.]
 [-4. -4. -4.]
 [-4. -4. -4.]]
[[ 0.  5. 12.]
 [21. 32. 45.]
 [60. 77. 96.]]
[[0.         0.2        0.33333333]
 [0.42857143 0.5        0.55555556]
 [0.6        0.63636364 0.66666667]]


2 次元配列 ```a``` と ```b``` があったときに，  
それぞれを行列と考えて行列積を求める方法は 3 種類．

1. ```np.dot``` 関数 ```np.dot```
2. ```a.dot(b)``` 配列 ```a``` のメソッド ```dot```
3. ```a@b``` 行列積の演算子 ```@``` (```Python``` 3.5 から導入)

In [37]:
print(np.dot(a,b))
print(a.dot(b))
print(a@b)

[[ 27.  30.  33.]
 [ 90. 102. 114.]
 [153. 174. 195.]]
[[ 27.  30.  33.]
 [ 90. 102. 114.]
 [153. 174. 195.]]
[[ 27.  30.  33.]
 [ 90. 102. 114.]
 [153. 174. 195.]]


形状が違う行列の積

In [38]:
a = np.arange(9.).reshape(3,3)
v = np.arange(1.,4.)
print(a)
print(v)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[1. 2. 3.]


In [39]:
print(np.dot(a,v))
print(np.dot(v,a))

[ 8. 26. 44.]
[24. 30. 36.]


配列の行数と列数を考慮して，うまく計算できるようにして計算している．

In [40]:
u = v.reshape(-1, 1) # 1 列の 2 次元配列
print(u)
print(np.dot(a,u))

[[1.]
 [2.]
 [3.]]
[[ 8.]
 [26.]
 [44.]]


In [41]:
# 順番を変えると，エラー
print(np.dot(u,a))

ValueError: ignored

In [42]:
w = v.reshape(1,-1) # 1 行の 2 次元配列
print(w)
print(np.dot(w,a))

[[1. 2. 3.]]
[[24. 30. 36.]]


配列同士の演算における少し複雑なブロードキャスト

In [43]:
a = np.arange(12.).reshape(4,3) # (4,3) の 2 次元配列
b = np.arange(3.).reshape(1,3) # (1,3) の 2 次元配列
c = np.arange(4.).reshape(4,1) # (4,1) の 2 次元配列
print(a)
print(b)
print(c)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[0. 1. 2.]]
[[0.]
 [1.]
 [2.]
 [3.]]


In [44]:
print(a+b)

[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]
 [ 9. 11. 13.]]


In [45]:
print(a*c)

[[ 0.  0.  0.]
 [ 3.  4.  5.]
 [12. 14. 16.]
 [27. 30. 33.]]


In [46]:
print(b-c)

[[ 0.  1.  2.]
 [-1.  0.  1.]
 [-2. -1.  0.]
 [-3. -2. -1.]]


2 次元配列が与えられたときにそれらにに項演算子を作用させることができるのは，  
二つの配列の形状の各次元の大きさが等しいか，片方が 1 である場合．

# 課題 211019-01

Numpy に習熟する．
0 から 9 までの整数を各要素に持つ 1 次元の Numpy 配列を考える．
それらの要素はランダムに決定されるものとする．
その配列を 2 個用意して，それぞれの間で同じ番号で値も等しい要素があるか，
またあるならその個数は幾つかを表示するスクリプトを作りましょう．

(参考)  
https://note.nkmk.me/python-numpy-random/  
https://note.nkmk.me/python-random-randrange-randint/

In [47]:
import numpy as np
# 乱数
x = np.random.rand() # 一個
print(x)
x = np.random.rand(3) # 要素数 3 の 1 次元配列
print(x)
x = np.random.rand(3, 5) # 3x5 の 2 次元配列
print(x)

0.9982913199410262
[0.01713062 0.46637575 0.20232625]
[[0.19019114 0.92488217 0.49237211 0.79425669 0.57206929]
 [0.63216093 0.13867221 0.93434174 0.06511729 0.38862227]
 [0.2023262  0.33736944 0.87658382 0.40449624 0.26397867]]


In [48]:
x = np.random.randint(10) # 1 個(範囲指定)
print(x)

x = np.random.randint(0, 10) # 1 個 (範囲指定 (上限下限))
print(x)

x = np.random.randint(0, 10, 5) # 複数 (範囲指定(上限下限), 個数)
print(x)

3
8
[1 6 7 1 4]


In [49]:
a = np.array([1, 2, 3, 0, 1])
b = np.array([0, 2, 0, 3, 1])

print(a)
print(b)
print(a==b)
print(a[a==b])


[1 2 3 0 1]
[0 2 0 3 1]
[False  True False False  True]
[2 1]


In [63]:
n = 10 # 要素数
x = np.random.randint(0, 10, n)
y = np.random.randint(0, 10, n)

n_e = x[x==y].size #同じ番号で値も等しい要素の数

print(x)
print(y)

if n_e != 0:
  print('同じ番号で値も等しい要素は', n_e, '個あり、それは', x[x==y])
else:
  print('同じ番号で値も等しい要素はこれらの中にはなかった')

[3 8 9 1 8 9 3 6 4 4]
[8 6 6 4 7 6 7 8 7 3]
同じ番号で値も等しい要素はこれらの中にはなかった


# NumPy / SciPy による線形代数

## 逆行列

下のベクトルを扱うことにする

$$
\left(\begin{array}{ccc}
    3 & 1 & 1\\
    1 & 2 & 1\\
    0 & -1 & 1
\end{array}\right)
$$

```numpy``` の下に ```linalg``` という線形代数のためのモジュールがある．

その中の ```inv``` という関数を使って上の行列の逆行列を求める．

In [64]:
import numpy as np

In [65]:
a = np.array([[3, 1, 1], [1,2,1], [0,-1,1]])
print(a)
print(np.linalg.inv(a))

[[ 3  1  1]
 [ 1  2  1]
 [ 0 -1  1]]
[[ 0.42857143 -0.28571429 -0.14285714]
 [-0.14285714  0.42857143 -0.28571429]
 [-0.14285714  0.42857143  0.71428571]]


試してみる

In [66]:
print(np.dot(a, np.linalg.inv(a))) # a, inv(a)
print(np.dot(np.linalg.inv(a), a)) # inv(a), a (掛ける順序を変えてみる）

[[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]
[[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]


大体 OK.  

計算機における数値演算では，実数の計算では，計算結果が 0 でなくて 0 の近似値として非常に小さな値になるときがあることがあることを思い出そう．  

## 連立方程式

次の方程式の解を数値的に求めたい．

$$
\left(\begin{array}{ccc}
    3 & 1 & 1\\
    1 & 2 & 1\\
    0 & -1 & 1  
\end{array}\right)
\left(\begin{array}{c}
    x\\
    y\\
    z
\end{array}\right)
=
\left(\begin{array}{c}
    1\\
    2\\
    3
\end{array}\right)
$$

逆関数を使う？  

In [67]:
b = [1,2,3]
a_inv = np.linalg.inv(a)
print(a_inv)
print(a@a_inv)
print(np.dot(a_inv,b))

[[ 0.42857143 -0.28571429 -0.14285714]
 [-0.14285714  0.42857143 -0.28571429]
 [-0.14285714  0.42857143  0.71428571]]
[[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]
[-0.57142857 -0.14285714  2.85714286]


それでもいい，が，それよりも高速で数値的に安定な手法がある．

→ 1 次方程式を解く関数 ```np.linalg.solve``` を使う

In [68]:
a = np.array([[3, 1, 1],[1, 2, 1],[0, -1, 1]])
b = np.array([1, 2, 3])
print(a)
print(b)
print(np.linalg.solve(a,b))

[[ 3  1  1]
 [ 1  2  1]
 [ 0 -1  1]]
[1 2 3]
[-0.57142857 -0.14285714  2.85714286]


詳細は省くが，逆行列を求めるアルゴリズムと1 次方程式を求める方程式は別．  
1 次方程式を解く方が高速かつ数値的安定なアルゴリズムが知られている．

ただし，これは 1 つの方程式を解くときにだけ効果がある方法．  
同じ係数の複数の方程式を解く場合にはあまりうまくない．

どうするか？ → LU 分解で行こう．

## LU 分解  

与えらえれた $n$ 次正方行列 $\boldsymbol A$ を 3 つの行列 $\boldsymbol P$ : 置換行列, $\boldsymbol L$ : 対角成分 1 の下三角行列, $\boldsymbol U$ : 上三角行列で表す．

置換行列 : 各行に 1 である成分が 1 つだけあり，他は 0 である行列  
下三角行列 : 対角成分より右上がすべて 0 であるような行列  
上三角行列 : 体格成分より左下がすべて 0 であるような行列

$\boldsymbol L$ は対角成分が 1 であるという条件もあるので，$\boldsymbol L$ と $\boldsymbol U$ は次のようになる．

$$
\boldsymbol{L}=\left(\begin{array}{ccccc}
 1 &   &   &   &  \\
 * & 1 &   &   &   \\
 * & * & 1 &   &   \\
 \vdots & \vdots & \vdots & \ddots &  \\
 * & * & * & \cdots & 1
 \end{array}\right)
$$
, 
$$
\boldsymbol{U}=\left(\begin{array}{ccccc}
 * & * & * & * & * \\
   & * & *  & * & * \\
   &   & \ddots & \vdots  & \vdots  \\
   &   &  & * & * \\
   &   &   &  & * 
 \end{array}\right)
$$

ここで $*$ はどんな値でもいいということを表す．



このような $\boldsymbol P$, $\boldsymbol L$, $\boldsymbol U$ を係数に持つ連立方程式は高速に解けることがわかっている．

元の方程式は $\boldsymbol Ax = \boldsymbol b$ なので，

$$
\boldsymbol{PLU}x = \boldsymbol b
$$

を満たす $\boldsymbol x$ を求めればいい．

そのために，次の方程式を解く
$$
\boldsymbol{Pz} = \boldsymbol b\\
\boldsymbol{Ly} = \boldsymbol z\\
\boldsymbol{Ux} = \boldsymbol y
$$

これで求められた $\boldsymbol x$ はもとの連立方程式の解になる．  
それぞれの方程式は効率的に解ける  
3 つの方程式の計算量 $\simeq$ n 次正方行列とベクトルとの積の計算量  

LU 分解のための計算量 $<$ $\boldsymbol{A}^{-1}$ を求める計算量

なので，LU 分解は $\boldsymbol A$ の逆行列を求めて解くよりも効率的


実際には，```SciPy``` に入っている LU 分解の関数 ```linalg.lu_factore``` と ```linalg.lu_solve``` を使えばよい．

In [71]:
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])
b = np.array([1, 2, 3])

from scipy import linalg # scipy.linalg のインポート

lu, p = linalg.lu_factor(a)

print(lu) # 上三角部分が U, 下三角部分（対角成分除く）が L
print(p)

print(linalg.lu_solve((lu,p), b))

[[ 3.          1.          1.        ]
 [ 0.33333333  1.66666667  0.66666667]
 [ 0.         -0.6         1.4       ]]
[0 1 2]
[-0.57142857 -0.14285714  2.85714286]


注意： ```numpy.linalg``` でなくて，```scipy.linalg``` を使っている

関数 ```lu_factor``` は LU 分解をして $\boldsymbol L$, $\boldsymbol U$, $\boldsymbol P$ に相当する行列を返す．  
$\boldsymbol L$ と $\boldsymbol U$ は 1 つの行列で表されて，戻り値は二つの行列のタプルになっている．  

関数 ```lu_solve``` は ```lu_factor``` の戻り値とベクトル $\boldsymbol b$ にあたる配列を受け取り，解を求める．



In [72]:
a = np.array([[1,2,1], [0,-1,1],[3,1,1]])
b = np.array([2, 3, 1])

from scipy import linalg # scipy.linalg のインポート

lu, p = linalg.lu_factor(a)

print(lu) # 上三角部分が U, 下三角部分（対角成分除く）が L
print(p)

print(linalg.lu_solve((lu,p), b))

[[ 3.          1.          1.        ]
 [ 0.33333333  1.66666667  0.66666667]
 [ 0.         -0.6         1.4       ]]
[2 2 2]
[-0.57142857 -0.14285714  2.85714286]


In [73]:
a = np.array([[3,1,1], [0,-1,1], [1,2,1]])
b = np.array([1, 3, 2])

from scipy import linalg # scipy.linalg のインポート

lu, p = linalg.lu_factor(a)

print(lu) # 上三角部分が U, 下三角部分（対角成分除く）が L
print(p)

print(linalg.lu_solve((lu,p), b))

[[ 3.          1.          1.        ]
 [ 0.33333333  1.66666667  0.66666667]
 [ 0.         -0.6         1.4       ]]
[0 2 2]
[-0.57142857 -0.14285714  2.85714286]


## 線形代数の練習問題
```Numpy```, ```SciPy``` で解こう．

## 問題 211019-02
下の行列の逆行列を求めよう．それが正しいことを自分で確認しよう．
```Numpy``` の ```np.linalg.inv()``` を使おう．

$$
(1)~~
\left(
    \begin{array}{cc}
        3 & 5 \\
        4 & 7 \\
    \end{array}
\right)
$$
  
$$
(2)~~~ 
\left(
    \begin{array}{ccc}
    2 & 1 & 3 \\
    4 & 5 & 4 \\
    3 & 1 & 5
    \end{array}
\right)
$$


In [85]:
import numpy as np

# (1)
a = np.array([[3, 5], [4, 7]])
a_inv = np.linalg.inv(a)

print('(1)の行列\n', a, '\nの逆行列は\n', a_inv, '\nであり、それはそれぞれの行列の内積が\n', np.dot(a, a_inv), '\nであることから確かめられる')

print()
# (2)
b = np.array([[2, 1, 3], [4, 5, 4], [3, 1, 5]])
b_inv = np.linalg.inv(b)
print('(2)の行列\n', b, '\nの逆行列は\n', b_inv, '\nであり、それはそれぞれの行列の内積が\n', np.dot(b, b_inv), '\nであることから確かめられる')

(1)の行列
 [[3 5]
 [4 7]] 
の逆行列は
 [[ 7. -5.]
 [-4.  3.]] 
であり、それはそれぞれの行列の内積が
 [[1. 0.]
 [0. 1.]] 
であることから確かめられる

(2)の行列
 [[2 1 3]
 [4 5 4]
 [3 1 5]] 
の逆行列は
 [[ 21.  -2. -11.]
 [ -8.   1.   4.]
 [-11.   1.   6.]] 
であり、それはそれぞれの行列の内積が
 [[ 1.00000000e+00 -4.44089210e-16 -1.77635684e-15]
 [ 7.10542736e-15  1.00000000e+00 -3.55271368e-15]
 [ 3.55271368e-15 -4.44089210e-16  1.00000000e+00]] 
であることから確かめられる


## 問題 211019-03
下の 2 次方程式の解を求めよう．それが正しいことを自分で確認しよう．
```Scipy``` の ```linalg.lu_factor()``` と ```linalg.lu_solve()``` を使おう．

```Numpy``` の ```np.linalg.inv()``` で求めた逆行列を使った方法でも確認してみよう

$$
(1)~~
\left(
    \begin{array}{ccc}
    2 & 1 & 3 \\
    4 & 5 & 4 \\
    3 & 1 & 5
    \end{array}
\right)
\left(
    \begin{array}{c}
    x_{0}\\
    x_{1}\\
    x_{2}
    \end{array}
\right)
=
\left(
    \begin{array}{c}
    0\\
    -2\\
    1
    \end{array}
\right)
$$  
$$
(2)~~~
\left(
    \begin{array}{cccc}
    8 & 16 & 24 & 32 \\
    2 & 7 & 12 & 17 \\
    6 & 17 & 32 & 59 \\
    7 & 22 & 46 & 105
    \end{array}
\right)
\left(
    \begin{array}{c}
    x_{0}\\
    x_{1}\\
    x_{2}\\
    x_{3}
    \end{array}
\right)
=
\left(
    \begin{array}{c}
    160\\
    70\\
    198\\
    291
    \end{array}
\right)
$$


In [93]:
import numpy as np

from scipy import linalg

# (1)
a = np.array([[2, 1, 3], [4, 5, 4], [3,1, 5]])
b = np.array([0, -2, 1])

lu, p = linalg.lu_factor(a)
print('(1)において\nLU分解で求めた答えは')
print(linalg.lu_solve((lu, p), b))
print('であり、\n逆行列で求めた答えは')
a_inv = np.linalg.inv(a)
print(np.dot(a_inv, b))
print('であり、一致した')

print()
#(2)
a = np.array([[8, 16, 24, 32], [2, 7, 12, 17], [6, 17, 32, 59], [7, 22, 46, 105]])
b = np.array([160, 70, 198, 291])
lu, p = linalg.lu_factor(a)
print('(2)において\nLU分解で求めた答えは')
print(linalg.lu_solve((lu, p), b))
print('であり、\n逆行列で求めた答えは')
a_inv = np.linalg.inv(a)
print(np.dot(a_inv, b))
print('であり、一致した')

(1)において
LU分解で求めた答えは
[-7.  2.  4.]
であり、
逆行列で求めた答えは
[-7.  2.  4.]
であり、一致した

(2)において
LU分解で求めた答えは
[4. 3. 2. 1.]
であり、
逆行列で求めた答えは
[4. 3. 2. 1.]
であり、一致した
